### ISSUE TITLE
Docker-compose with flask app.py (flask example)

### ISSUE THREAD

**Issue by Akaori** [chunky-monkeys/keycloak-client#52]
Hi, 

I'm building a web application with Flask and want to use Keycloak to provide access.

1- First I have created a docker-compose file:

```
version: '3.1'


volumes:
  postgres_data:
      driver: local


services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - test
  keycloak:
      image: jboss/keycloak:10.0.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: fosstechnixx
        KEYCLOAK_PASSWORD: fosstechnixx@123  
      networks:
        - test  
      ports:
        - 80:8080
      depends_on:
        - postgres
  flask:
      build: .
      volumes:
        - ./json:/json
      ports:
        - "5000:5000"
      depends_on: 
        - keycloak
        - postgres
      networks:
        - test

networks:
  test:
    driver: bridge

```

2 - After setting up the server, I have created a client for the application. Setting "Access Type" to "confidential", Setting the valid redirect URIs (mandatory), and clicking "Save".
 
Then I go to "Installation", select "Keycloak OIDC JSON" as "Format Option" and download the file.

3- When I try to access localhost:5000, which is this app.py [example](https://github.com/chunky-monkeys/keycloak-client/blob/master/examples/flask-app/app.py), I got the following error:

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /auth/realms/test/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe193f40e20>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Could someone help me, providing an example that works fine with this docker-compose ?
